//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드는 wsdl, 버전=4.0.30319.1에서 자동 생성되었습니다.
// 
namespace _1C.v8241.CustomerVehicleChange {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerVehicleChangeSoapBinding", Namespace="http://wa.dms.webservice/")]
    public partial class CustomerVehicleChange : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallCustomerVehicleChangeOperationCompleted;
        
        /// <remarks/>
        public CustomerVehicleChange() {
            this.Url = "http://192.168.32.2/rtr-atest/ws/customervehiclechange.1cws";
        }
        
        /// <remarks/>
        public event CallCustomerVehicleChangeCompletedEventHandler CallCustomerVehicleChangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wa.dms.webservice/#CustomerVehicleChange:CustomerVehicleChange", RequestElementName="CustomerVehicleChange", RequestNamespace="http://wa.dms.webservice/", ResponseElementName="CustomerVehicleChangeResponse", ResponseNamespace="http://wa.dms.webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public CustomerVehicleChangeResponse CallCustomerVehicleChange(CustomerVehicleChangeRequest CustomerVehicleChangeRequest) {
            object[] results = this.Invoke("CallCustomerVehicleChange", new object[] {
                        CustomerVehicleChangeRequest});
            return ((CustomerVehicleChangeResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallCustomerVehicleChange(CustomerVehicleChangeRequest CustomerVehicleChangeRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CallCustomerVehicleChange", new object[] {
                        CustomerVehicleChangeRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerVehicleChangeResponse EndCallCustomerVehicleChange(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerVehicleChangeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CallCustomerVehicleChangeAsync(CustomerVehicleChangeRequest CustomerVehicleChangeRequest) {
            this.CallCustomerVehicleChangeAsync(CustomerVehicleChangeRequest, null);
        }
        
        /// <remarks/>
        public void CallCustomerVehicleChangeAsync(CustomerVehicleChangeRequest CustomerVehicleChangeRequest, object userState) {
            if ((this.CallCustomerVehicleChangeOperationCompleted == null)) {
                this.CallCustomerVehicleChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallCustomerVehicleChangeOperationCompleted);
            }
            this.InvokeAsync("CallCustomerVehicleChange", new object[] {
                        CustomerVehicleChangeRequest}, this.CallCustomerVehicleChangeOperationCompleted, userState);
        }
        
        private void OnCallCustomerVehicleChangeOperationCompleted(object arg) {
            if ((this.CallCustomerVehicleChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallCustomerVehicleChangeCompleted(this, new CallCustomerVehicleChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleChangeRequest {
        
        private TransactionHeader transactionHeaderField;
        
        private CustomerVehicleChange1 customerVehicleChangeField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public CustomerVehicleChange1 CustomerVehicleChange {
            get {
                return this.customerVehicleChangeField;
            }
            set {
                this.customerVehicleChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class TransactionHeader {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class ResultMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleChangeResponse {
        
        private TransactionHeader transactionHeaderField;
        
        private ResultMessage resultMessageField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResultMessage ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Campaign {
        
        private string campaignIDField;
        
        private string campaignDescriptionField;
        
        private string campaignPerformedField;
        
        /// <remarks/>
        public string CampaignID {
            get {
                return this.campaignIDField;
            }
            set {
                this.campaignIDField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignDescription {
            get {
                return this.campaignDescriptionField;
            }
            set {
                this.campaignDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignPerformed {
            get {
                return this.campaignPerformedField;
            }
            set {
                this.campaignPerformedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Vehicle {
        
        private string dMSVehicleNoField;
        
        private string vINField;
        
        private string stockNumberField;
        
        private string licensePlateNoField;
        
        private string makeField;
        
        private string modelCodeField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        private string lastMileageField;
        
        private string colorField;
        
        private string vehicleTypeField;
        
        private string engineTypeField;
        
        private string fuelTypeField;
        
        private string cylindersField;
        
        private string trimField;
        
        private string fullModelNameField;
        
        private System.DateTime insuranceDateField;
        
        private bool insuranceDateFieldSpecified;
        
        private System.DateTime dateInServiceField;
        
        private bool dateInServiceFieldSpecified;
        
        private System.DateTime dateDeliveredField;
        
        private bool dateDeliveredFieldSpecified;
        
        private System.DateTime warrantyStartDateField;
        
        private bool warrantyStartDateFieldSpecified;
        
        private string warrantyMonthsField;
        
        private string warrantyMilesField;
        
        private string licenseNumberField;
        
        private System.DateTime lastServiceDateField;
        
        private bool lastServiceDateFieldSpecified;
        
        private System.DateTime extendedWarrantyField;
        
        private bool extendedWarrantyFieldSpecified;
        
        private string declinedJobField;
        
        private string pendingJobField;
        
        private string displayDescriptionField;
        
        private Campaign[] campaignsField;
        
        private System.DateTime extendedWarrantyExpireDateField;
        
        private bool extendedWarrantyExpireDateFieldSpecified;
        
        private string engineNoField;
        
        /// <remarks/>
        public string DMSVehicleNo {
            get {
                return this.dMSVehicleNoField;
            }
            set {
                this.dMSVehicleNoField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        public string StockNumber {
            get {
                return this.stockNumberField;
            }
            set {
                this.stockNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LicensePlateNo {
            get {
                return this.licensePlateNoField;
            }
            set {
                this.licensePlateNoField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string ModelCode {
            get {
                return this.modelCodeField;
            }
            set {
                this.modelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
        
        /// <remarks/>
        public string LastMileage {
            get {
                return this.lastMileageField;
            }
            set {
                this.lastMileageField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EngineType {
            get {
                return this.engineTypeField;
            }
            set {
                this.engineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FuelType {
            get {
                return this.fuelTypeField;
            }
            set {
                this.fuelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Cylinders {
            get {
                return this.cylindersField;
            }
            set {
                this.cylindersField = value;
            }
        }
        
        /// <remarks/>
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string FullModelName {
            get {
                return this.fullModelNameField;
            }
            set {
                this.fullModelNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsuranceDate {
            get {
                return this.insuranceDateField;
            }
            set {
                this.insuranceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsuranceDateSpecified {
            get {
                return this.insuranceDateFieldSpecified;
            }
            set {
                this.insuranceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateInService {
            get {
                return this.dateInServiceField;
            }
            set {
                this.dateInServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInServiceSpecified {
            get {
                return this.dateInServiceFieldSpecified;
            }
            set {
                this.dateInServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateDelivered {
            get {
                return this.dateDeliveredField;
            }
            set {
                this.dateDeliveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateDeliveredSpecified {
            get {
                return this.dateDeliveredFieldSpecified;
            }
            set {
                this.dateDeliveredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WarrantyStartDate {
            get {
                return this.warrantyStartDateField;
            }
            set {
                this.warrantyStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarrantyStartDateSpecified {
            get {
                return this.warrantyStartDateFieldSpecified;
            }
            set {
                this.warrantyStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string WarrantyMonths {
            get {
                return this.warrantyMonthsField;
            }
            set {
                this.warrantyMonthsField = value;
            }
        }
        
        /// <remarks/>
        public string WarrantyMiles {
            get {
                return this.warrantyMilesField;
            }
            set {
                this.warrantyMilesField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastServiceDate {
            get {
                return this.lastServiceDateField;
            }
            set {
                this.lastServiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastServiceDateSpecified {
            get {
                return this.lastServiceDateFieldSpecified;
            }
            set {
                this.lastServiceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExtendedWarranty {
            get {
                return this.extendedWarrantyField;
            }
            set {
                this.extendedWarrantyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtendedWarrantySpecified {
            get {
                return this.extendedWarrantyFieldSpecified;
            }
            set {
                this.extendedWarrantyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DeclinedJob {
            get {
                return this.declinedJobField;
            }
            set {
                this.declinedJobField = value;
            }
        }
        
        /// <remarks/>
        public string PendingJob {
            get {
                return this.pendingJobField;
            }
            set {
                this.pendingJobField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayDescription {
            get {
                return this.displayDescriptionField;
            }
            set {
                this.displayDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public Campaign[] Campaigns {
            get {
                return this.campaignsField;
            }
            set {
                this.campaignsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExtendedWarrantyExpireDate {
            get {
                return this.extendedWarrantyExpireDateField;
            }
            set {
                this.extendedWarrantyExpireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtendedWarrantyExpireDateSpecified {
            get {
                return this.extendedWarrantyExpireDateFieldSpecified;
            }
            set {
                this.extendedWarrantyExpireDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EngineNo {
            get {
                return this.engineNoField;
            }
            set {
                this.engineNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CorporateInfo {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class SpecialMessage {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Contact {
        
        private string contactTypeField;
        
        private string contactValueField;
        
        private string contactMethodYNField;
        
        /// <remarks/>
        public string ContactType {
            get {
                return this.contactTypeField;
            }
            set {
                this.contactTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactValue {
            get {
                return this.contactValueField;
            }
            set {
                this.contactValueField = value;
            }
        }
        
        /// <remarks/>
        public string ContactMethodYN {
            get {
                return this.contactMethodYNField;
            }
            set {
                this.contactMethodYNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Address {
        
        private string addressTypeField;
        
        private string fullAddressField;
        
        private string zipCodeField;
        
        private string regionField;
        
        private string districtField;
        
        private string cityField;
        
        private string localityField;
        
        private string streetField;
        
        private string houseField;
        
        private string housingField;
        
        private string flatField;
        
        /// <remarks/>
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FullAddress {
            get {
                return this.fullAddressField;
            }
            set {
                this.fullAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string House {
            get {
                return this.houseField;
            }
            set {
                this.houseField = value;
            }
        }
        
        /// <remarks/>
        public string Housing {
            get {
                return this.housingField;
            }
            set {
                this.housingField = value;
            }
        }
        
        /// <remarks/>
        public string Flat {
            get {
                return this.flatField;
            }
            set {
                this.flatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Customer {
        
        private string customerInfoTypeField;
        
        private string dMSCustomerNoField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string firstNameField;
        
        private string fullNameField;
        
        private string salutationField;
        
        private string genderField;
        
        private string cardNoField;
        
        private string emailField;
        
        private Address[] addressesField;
        
        private Contact[] contactsField;
        
        private SpecialMessage specialMessageField;
        
        private CorporateInfo[] corporateInfosField;
        
        /// <remarks/>
        public string CustomerInfoType {
            get {
                return this.customerInfoTypeField;
            }
            set {
                this.customerInfoTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCustomerNo {
            get {
                return this.dMSCustomerNoField;
            }
            set {
                this.dMSCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string CardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public Contact[] Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        public SpecialMessage SpecialMessage {
            get {
                return this.specialMessageField;
            }
            set {
                this.specialMessageField = value;
            }
        }
        
        /// <remarks/>
        public CorporateInfo[] CorporateInfos {
            get {
                return this.corporateInfosField;
            }
            set {
                this.corporateInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CustomerVehicleChange", Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleChange1 {
        
        private Customer customerField;
        
        private Vehicle vehicleField;
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CallCustomerVehicleChangeCompletedEventHandler(object sender, CallCustomerVehicleChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallCustomerVehicleChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallCustomerVehicleChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerVehicleChangeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerVehicleChangeResponse)(this.results[0]));
            }
        }
    }
}
