//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.34209에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace WA.v2.WS_Print {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PrintSoap", Namespace="http://wa.dms.webservice/")]
    public partial class Print : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PrintRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Print() {
            this.Url = global::WA.v2.Properties.Settings.Default.WA_v2_WS_Print_Print;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PrintRequestCompletedEventHandler PrintRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wa.dms.webservice/PrintRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PrintResponse", Namespace="http://wa.dms.webservice/PrintResponse", IsNullable=true)]
        public PrintResponse PrintRequest([System.Xml.Serialization.XmlElementAttribute("PrintRequest", Namespace="http://wa.dms.webservice/PrintRequest", IsNullable=true)] PrintRequest PrintRequest1) {
            object[] results = this.Invoke("PrintRequest", new object[] {
                        PrintRequest1});
            return ((PrintResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PrintRequestAsync(PrintRequest PrintRequest1) {
            this.PrintRequestAsync(PrintRequest1, null);
        }
        
        /// <remarks/>
        public void PrintRequestAsync(PrintRequest PrintRequest1, object userState) {
            if ((this.PrintRequestOperationCompleted == null)) {
                this.PrintRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintRequestOperationCompleted);
            }
            this.InvokeAsync("PrintRequest", new object[] {
                        PrintRequest1}, this.PrintRequestOperationCompleted, userState);
        }
        
        private void OnPrintRequestOperationCompleted(object arg) {
            if ((this.PrintRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintRequestCompleted(this, new PrintRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class PrintRequest {
        
        private TransactionHeader transactionHeaderField;
        
        private Print1 printField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public Print1 Print {
            get {
                return this.printField;
            }
            set {
                this.printField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class TransactionHeader {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.Nullable<System.DateTime> transactionDateTimeUTCField;
        
        private System.Nullable<System.DateTime> transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintResponse")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintResponse")]
    public partial class ResultMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TransactionHeader", Namespace="http://wa.dms.webservice/PrintResponse")]
    public partial class TransactionHeader1 {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.Nullable<System.DateTime> transactionDateTimeUTCField;
        
        private System.Nullable<System.DateTime> transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintResponse")]
    public partial class PrintResponse {
        
        private TransactionHeader1 transactionHeaderField;
        
        private ResultMessage resultMessageField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public TransactionHeader1 TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResultMessage ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class Summary {
        
        private string completedWorkConsistentWithTheStatedField;
        
        private string replacedPartsMatchesWithWorkDoneAndPackedProperlyField;
        
        private string theVehicleIsSuitableForUseField;
        
        private string fillInFinalInspectionListAndSignField;
        
        private string cleanCarInsideAndOutField;
        
        private string toSignRepairOrderAndGiveItSAField;
        
        /// <remarks/>
        public string CompletedWorkConsistentWithTheStated {
            get {
                return this.completedWorkConsistentWithTheStatedField;
            }
            set {
                this.completedWorkConsistentWithTheStatedField = value;
            }
        }
        
        /// <remarks/>
        public string ReplacedPartsMatchesWithWorkDoneAndPackedProperly {
            get {
                return this.replacedPartsMatchesWithWorkDoneAndPackedProperlyField;
            }
            set {
                this.replacedPartsMatchesWithWorkDoneAndPackedProperlyField = value;
            }
        }
        
        /// <remarks/>
        public string TheVehicleIsSuitableForUse {
            get {
                return this.theVehicleIsSuitableForUseField;
            }
            set {
                this.theVehicleIsSuitableForUseField = value;
            }
        }
        
        /// <remarks/>
        public string FillInFinalInspectionListAndSign {
            get {
                return this.fillInFinalInspectionListAndSignField;
            }
            set {
                this.fillInFinalInspectionListAndSignField = value;
            }
        }
        
        /// <remarks/>
        public string CleanCarInsideAndOut {
            get {
                return this.cleanCarInsideAndOutField;
            }
            set {
                this.cleanCarInsideAndOutField = value;
            }
        }
        
        /// <remarks/>
        public string ToSignRepairOrderAndGiveItSA {
            get {
                return this.toSignRepairOrderAndGiveItSAField;
            }
            set {
                this.toSignRepairOrderAndGiveItSAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class StandTest {
        
        private string brakesField;
        
        private string shocksField;
        
        private string correctnessWayOfCarMovingField;
        
        /// <remarks/>
        public string Brakes {
            get {
                return this.brakesField;
            }
            set {
                this.brakesField = value;
            }
        }
        
        /// <remarks/>
        public string Shocks {
            get {
                return this.shocksField;
            }
            set {
                this.shocksField = value;
            }
        }
        
        /// <remarks/>
        public string CorrectnessWayOfCarMoving {
            get {
                return this.correctnessWayOfCarMovingField;
            }
            set {
                this.correctnessWayOfCarMovingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class RoadTest {
        
        private string correctnessOfEngineWorksField;
        
        private string correctnessWorkingOfClutchAndTransmissionField;
        
        private string theCorrectPositionOfTheSteeringWheelField;
        
        private string lackOfNoiseVibrationAndDynamicImpactField;
        
        /// <remarks/>
        public string CorrectnessOfEngineWorks {
            get {
                return this.correctnessOfEngineWorksField;
            }
            set {
                this.correctnessOfEngineWorksField = value;
            }
        }
        
        /// <remarks/>
        public string CorrectnessWorkingOfClutchAndTransmission {
            get {
                return this.correctnessWorkingOfClutchAndTransmissionField;
            }
            set {
                this.correctnessWorkingOfClutchAndTransmissionField = value;
            }
        }
        
        /// <remarks/>
        public string TheCorrectPositionOfTheSteeringWheel {
            get {
                return this.theCorrectPositionOfTheSteeringWheelField;
            }
            set {
                this.theCorrectPositionOfTheSteeringWheelField = value;
            }
        }
        
        /// <remarks/>
        public string LackOfNoiseVibrationAndDynamicImpact {
            get {
                return this.lackOfNoiseVibrationAndDynamicImpactField;
            }
            set {
                this.lackOfNoiseVibrationAndDynamicImpactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class UnderHoodInspection {
        
        private string cleanlinessOfEngineField;
        
        private string absenceOfLeakageField;
        
        private string tighteningTorqueOfOilFillerCapsAndRadiatorField;
        
        private string cleanlinessAndTighteningOfBatteryTerminalsField;
        
        private string levelsOfTechnicalLiquidsField;
        
        private string existenceOfSpecialTagField;
        
        private string checkingOfCorrectnessOfHeadlightsField;
        
        /// <remarks/>
        public string CleanlinessOfEngine {
            get {
                return this.cleanlinessOfEngineField;
            }
            set {
                this.cleanlinessOfEngineField = value;
            }
        }
        
        /// <remarks/>
        public string AbsenceOfLeakage {
            get {
                return this.absenceOfLeakageField;
            }
            set {
                this.absenceOfLeakageField = value;
            }
        }
        
        /// <remarks/>
        public string TighteningTorqueOfOilFillerCapsAndRadiator {
            get {
                return this.tighteningTorqueOfOilFillerCapsAndRadiatorField;
            }
            set {
                this.tighteningTorqueOfOilFillerCapsAndRadiatorField = value;
            }
        }
        
        /// <remarks/>
        public string CleanlinessAndTighteningOfBatteryTerminals {
            get {
                return this.cleanlinessAndTighteningOfBatteryTerminalsField;
            }
            set {
                this.cleanlinessAndTighteningOfBatteryTerminalsField = value;
            }
        }
        
        /// <remarks/>
        public string LevelsOfTechnicalLiquids {
            get {
                return this.levelsOfTechnicalLiquidsField;
            }
            set {
                this.levelsOfTechnicalLiquidsField = value;
            }
        }
        
        /// <remarks/>
        public string ExistenceOfSpecialTag {
            get {
                return this.existenceOfSpecialTagField;
            }
            set {
                this.existenceOfSpecialTagField = value;
            }
        }
        
        /// <remarks/>
        public string CheckingOfCorrectnessOfHeadlights {
            get {
                return this.checkingOfCorrectnessOfHeadlightsField;
            }
            set {
                this.checkingOfCorrectnessOfHeadlightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class CheckInsideOutside {
        
        private string damagesOnBodyAndPaintField;
        
        private string exteriorLightingField;
        
        private string wiperAndWasherNozzlesField;
        
        private string hornHandbrakeAndSeatBeltsField;
        
        private string settingsOfClockAndMediaSystemField;
        
        private string absenceOfCautionIndicatorsOnTheDashboardField;
        
        private string doorsLocksAndWindowLiftsField;
        
        private string tighteningTorqueOfWheelNutsField;
        
        private string airPressureInTheTiresAndSpareWheelField;
        
        /// <remarks/>
        public string DamagesOnBodyAndPaint {
            get {
                return this.damagesOnBodyAndPaintField;
            }
            set {
                this.damagesOnBodyAndPaintField = value;
            }
        }
        
        /// <remarks/>
        public string ExteriorLighting {
            get {
                return this.exteriorLightingField;
            }
            set {
                this.exteriorLightingField = value;
            }
        }
        
        /// <remarks/>
        public string WiperAndWasherNozzles {
            get {
                return this.wiperAndWasherNozzlesField;
            }
            set {
                this.wiperAndWasherNozzlesField = value;
            }
        }
        
        /// <remarks/>
        public string HornHandbrakeAndSeatBelts {
            get {
                return this.hornHandbrakeAndSeatBeltsField;
            }
            set {
                this.hornHandbrakeAndSeatBeltsField = value;
            }
        }
        
        /// <remarks/>
        public string SettingsOfClockAndMediaSystem {
            get {
                return this.settingsOfClockAndMediaSystemField;
            }
            set {
                this.settingsOfClockAndMediaSystemField = value;
            }
        }
        
        /// <remarks/>
        public string AbsenceOfCautionIndicatorsOnTheDashboard {
            get {
                return this.absenceOfCautionIndicatorsOnTheDashboardField;
            }
            set {
                this.absenceOfCautionIndicatorsOnTheDashboardField = value;
            }
        }
        
        /// <remarks/>
        public string DoorsLocksAndWindowLifts {
            get {
                return this.doorsLocksAndWindowLiftsField;
            }
            set {
                this.doorsLocksAndWindowLiftsField = value;
            }
        }
        
        /// <remarks/>
        public string TighteningTorqueOfWheelNuts {
            get {
                return this.tighteningTorqueOfWheelNutsField;
            }
            set {
                this.tighteningTorqueOfWheelNutsField = value;
            }
        }
        
        /// <remarks/>
        public string AirPressureInTheTiresAndSpareWheel {
            get {
                return this.airPressureInTheTiresAndSpareWheelField;
            }
            set {
                this.airPressureInTheTiresAndSpareWheelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class InspectionUnderTheVehicle {
        
        private string absenseOfLeakageField;
        
        private string brakeAndFuelPipesAndHosesField;
        
        private string crankcaseProtectionField;
        
        private string tighteningTorqueOfDrainPlugsAndBrakeCalipersField;
        
        /// <remarks/>
        public string AbsenseOfLeakage {
            get {
                return this.absenseOfLeakageField;
            }
            set {
                this.absenseOfLeakageField = value;
            }
        }
        
        /// <remarks/>
        public string BrakeAndFuelPipesAndHoses {
            get {
                return this.brakeAndFuelPipesAndHosesField;
            }
            set {
                this.brakeAndFuelPipesAndHosesField = value;
            }
        }
        
        /// <remarks/>
        public string CrankcaseProtection {
            get {
                return this.crankcaseProtectionField;
            }
            set {
                this.crankcaseProtectionField = value;
            }
        }
        
        /// <remarks/>
        public string TighteningTorqueOfDrainPlugsAndBrakeCalipers {
            get {
                return this.tighteningTorqueOfDrainPlugsAndBrakeCalipersField;
            }
            set {
                this.tighteningTorqueOfDrainPlugsAndBrakeCalipersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class PreparingForFinalInspection {
        
        private string lookThrowTheWorkingDocumentationField;
        
        private string lookThrowTheHistoryOfServiceField;
        
        /// <remarks/>
        public string LookThrowTheWorkingDocumentation {
            get {
                return this.lookThrowTheWorkingDocumentationField;
            }
            set {
                this.lookThrowTheWorkingDocumentationField = value;
            }
        }
        
        /// <remarks/>
        public string LookThrowTheHistoryOfService {
            get {
                return this.lookThrowTheHistoryOfServiceField;
            }
            set {
                this.lookThrowTheHistoryOfServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class FinalInspection {
        
        private PreparingForFinalInspection preparingForFinalInspectionField;
        
        private InspectionUnderTheVehicle inspectionUnderTheVehicleField;
        
        private CheckInsideOutside checkInsideOutsideField;
        
        private UnderHoodInspection underHoodInspectionField;
        
        private RoadTest roadTestField;
        
        private StandTest standTestField;
        
        private Summary summaryField;
        
        /// <remarks/>
        public PreparingForFinalInspection PreparingForFinalInspection {
            get {
                return this.preparingForFinalInspectionField;
            }
            set {
                this.preparingForFinalInspectionField = value;
            }
        }
        
        /// <remarks/>
        public InspectionUnderTheVehicle InspectionUnderTheVehicle {
            get {
                return this.inspectionUnderTheVehicleField;
            }
            set {
                this.inspectionUnderTheVehicleField = value;
            }
        }
        
        /// <remarks/>
        public CheckInsideOutside CheckInsideOutside {
            get {
                return this.checkInsideOutsideField;
            }
            set {
                this.checkInsideOutsideField = value;
            }
        }
        
        /// <remarks/>
        public UnderHoodInspection UnderHoodInspection {
            get {
                return this.underHoodInspectionField;
            }
            set {
                this.underHoodInspectionField = value;
            }
        }
        
        /// <remarks/>
        public RoadTest RoadTest {
            get {
                return this.roadTestField;
            }
            set {
                this.roadTestField = value;
            }
        }
        
        /// <remarks/>
        public StandTest StandTest {
            get {
                return this.standTestField;
            }
            set {
                this.standTestField = value;
            }
        }
        
        /// <remarks/>
        public Summary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class AdditionalEquipment {
        
        private string securitySystemWithEngineImmobilizerField;
        
        private string secretNutsOnWheelsField;
        
        /// <remarks/>
        public string SecuritySystemWithEngineImmobilizer {
            get {
                return this.securitySystemWithEngineImmobilizerField;
            }
            set {
                this.securitySystemWithEngineImmobilizerField = value;
            }
        }
        
        /// <remarks/>
        public string SecretNutsOnWheels {
            get {
                return this.secretNutsOnWheelsField;
            }
            set {
                this.secretNutsOnWheelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class Complectation {
        
        private string additionalWheelField;
        
        private string standardToolkitField;
        
        private string jackField;
        
        private string roadkitField;
        
        private string firstAidkitField;
        
        private string ashtrayField;
        
        private string cigaretteLighterField;
        
        /// <remarks/>
        public string AdditionalWheel {
            get {
                return this.additionalWheelField;
            }
            set {
                this.additionalWheelField = value;
            }
        }
        
        /// <remarks/>
        public string StandardToolkit {
            get {
                return this.standardToolkitField;
            }
            set {
                this.standardToolkitField = value;
            }
        }
        
        /// <remarks/>
        public string Jack {
            get {
                return this.jackField;
            }
            set {
                this.jackField = value;
            }
        }
        
        /// <remarks/>
        public string Roadkit {
            get {
                return this.roadkitField;
            }
            set {
                this.roadkitField = value;
            }
        }
        
        /// <remarks/>
        public string FirstAidkit {
            get {
                return this.firstAidkitField;
            }
            set {
                this.firstAidkitField = value;
            }
        }
        
        /// <remarks/>
        public string Ashtray {
            get {
                return this.ashtrayField;
            }
            set {
                this.ashtrayField = value;
            }
        }
        
        /// <remarks/>
        public string CigaretteLighter {
            get {
                return this.cigaretteLighterField;
            }
            set {
                this.cigaretteLighterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class InspectionOfBodyAndWindows {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class VehicleIsFullyLifted {
        
        private string driveShaftsField;
        
        private string frontSuspensionField;
        
        private string rearSuspensionField;
        
        private string exhaustSystemField;
        
        private string leakageOfTechnicalLiquidsField;
        
        /// <remarks/>
        public string DriveShafts {
            get {
                return this.driveShaftsField;
            }
            set {
                this.driveShaftsField = value;
            }
        }
        
        /// <remarks/>
        public string FrontSuspension {
            get {
                return this.frontSuspensionField;
            }
            set {
                this.frontSuspensionField = value;
            }
        }
        
        /// <remarks/>
        public string RearSuspension {
            get {
                return this.rearSuspensionField;
            }
            set {
                this.rearSuspensionField = value;
            }
        }
        
        /// <remarks/>
        public string ExhaustSystem {
            get {
                return this.exhaustSystemField;
            }
            set {
                this.exhaustSystemField = value;
            }
        }
        
        /// <remarks/>
        public string LeakageOfTechnicalLiquids {
            get {
                return this.leakageOfTechnicalLiquidsField;
            }
            set {
                this.leakageOfTechnicalLiquidsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class VehicleIsPartlyLifted {
        
        private string steeringSystemField;
        
        private string frontWheelBearingsField;
        
        private string rearWheelBearingsField;
        
        private string shockAbsorbersField;
        
        private string frontBrakeDiscsField;
        
        private string rearBrakeDiscsField;
        
        private string frontBrakePadsField;
        
        private string rearBrakePadsField;
        
        private string tyresWheelDiscsField;
        
        private string radiatorsField;
        
        /// <remarks/>
        public string SteeringSystem {
            get {
                return this.steeringSystemField;
            }
            set {
                this.steeringSystemField = value;
            }
        }
        
        /// <remarks/>
        public string FrontWheelBearings {
            get {
                return this.frontWheelBearingsField;
            }
            set {
                this.frontWheelBearingsField = value;
            }
        }
        
        /// <remarks/>
        public string RearWheelBearings {
            get {
                return this.rearWheelBearingsField;
            }
            set {
                this.rearWheelBearingsField = value;
            }
        }
        
        /// <remarks/>
        public string ShockAbsorbers {
            get {
                return this.shockAbsorbersField;
            }
            set {
                this.shockAbsorbersField = value;
            }
        }
        
        /// <remarks/>
        public string FrontBrakeDiscs {
            get {
                return this.frontBrakeDiscsField;
            }
            set {
                this.frontBrakeDiscsField = value;
            }
        }
        
        /// <remarks/>
        public string RearBrakeDiscs {
            get {
                return this.rearBrakeDiscsField;
            }
            set {
                this.rearBrakeDiscsField = value;
            }
        }
        
        /// <remarks/>
        public string FrontBrakePads {
            get {
                return this.frontBrakePadsField;
            }
            set {
                this.frontBrakePadsField = value;
            }
        }
        
        /// <remarks/>
        public string RearBrakePads {
            get {
                return this.rearBrakePadsField;
            }
            set {
                this.rearBrakePadsField = value;
            }
        }
        
        /// <remarks/>
        public string TyresWheelDiscs {
            get {
                return this.tyresWheelDiscsField;
            }
            set {
                this.tyresWheelDiscsField = value;
            }
        }
        
        /// <remarks/>
        public string Radiators {
            get {
                return this.radiatorsField;
            }
            set {
                this.radiatorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class UnderhoodInspection {
        
        private string airFilterField;
        
        private string oilLevelInEngineField;
        
        private string driveBeltsField;
        
        private string pipelinesLeakageField;
        
        private string batteryField;
        
        /// <remarks/>
        public string AirFilter {
            get {
                return this.airFilterField;
            }
            set {
                this.airFilterField = value;
            }
        }
        
        /// <remarks/>
        public string OilLevelInEngine {
            get {
                return this.oilLevelInEngineField;
            }
            set {
                this.oilLevelInEngineField = value;
            }
        }
        
        /// <remarks/>
        public string DriveBelts {
            get {
                return this.driveBeltsField;
            }
            set {
                this.driveBeltsField = value;
            }
        }
        
        /// <remarks/>
        public string PipelinesLeakage {
            get {
                return this.pipelinesLeakageField;
            }
            set {
                this.pipelinesLeakageField = value;
            }
        }
        
        /// <remarks/>
        public string Battery {
            get {
                return this.batteryField;
            }
            set {
                this.batteryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class ExternalInspection {
        
        private string externalLightsField;
        
        /// <remarks/>
        public string ExternalLights {
            get {
                return this.externalLightsField;
            }
            set {
                this.externalLightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class LevelOfFuelInTank {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class InternalInspection {
        
        private string parkingBrakeField;
        
        private string safetyBeltsField;
        
        private string hornField;
        
        private string conditionSystemField;
        
        private string wipersWashersField;
        
        /// <remarks/>
        public string ParkingBrake {
            get {
                return this.parkingBrakeField;
            }
            set {
                this.parkingBrakeField = value;
            }
        }
        
        /// <remarks/>
        public string SafetyBelts {
            get {
                return this.safetyBeltsField;
            }
            set {
                this.safetyBeltsField = value;
            }
        }
        
        /// <remarks/>
        public string Horn {
            get {
                return this.hornField;
            }
            set {
                this.hornField = value;
            }
        }
        
        /// <remarks/>
        public string ConditionSystem {
            get {
                return this.conditionSystemField;
            }
            set {
                this.conditionSystemField = value;
            }
        }
        
        /// <remarks/>
        public string WipersWashers {
            get {
                return this.wipersWashersField;
            }
            set {
                this.wipersWashersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class VHC {
        
        private InternalInspection internalInspectionField;
        
        private LevelOfFuelInTank levelOfFuelInTankField;
        
        private ExternalInspection externalInspectionField;
        
        private UnderhoodInspection underhoodInspectionField;
        
        private VehicleIsPartlyLifted vehicleIsPartlyLiftedField;
        
        private VehicleIsFullyLifted vehicleIsFullyLiftedField;
        
        private InspectionOfBodyAndWindows inspectionOfBodyAndWindowsField;
        
        private Complectation complectationField;
        
        private AdditionalEquipment additionalEquipmentField;
        
        /// <remarks/>
        public InternalInspection InternalInspection {
            get {
                return this.internalInspectionField;
            }
            set {
                this.internalInspectionField = value;
            }
        }
        
        /// <remarks/>
        public LevelOfFuelInTank LevelOfFuelInTank {
            get {
                return this.levelOfFuelInTankField;
            }
            set {
                this.levelOfFuelInTankField = value;
            }
        }
        
        /// <remarks/>
        public ExternalInspection ExternalInspection {
            get {
                return this.externalInspectionField;
            }
            set {
                this.externalInspectionField = value;
            }
        }
        
        /// <remarks/>
        public UnderhoodInspection UnderhoodInspection {
            get {
                return this.underhoodInspectionField;
            }
            set {
                this.underhoodInspectionField = value;
            }
        }
        
        /// <remarks/>
        public VehicleIsPartlyLifted VehicleIsPartlyLifted {
            get {
                return this.vehicleIsPartlyLiftedField;
            }
            set {
                this.vehicleIsPartlyLiftedField = value;
            }
        }
        
        /// <remarks/>
        public VehicleIsFullyLifted VehicleIsFullyLifted {
            get {
                return this.vehicleIsFullyLiftedField;
            }
            set {
                this.vehicleIsFullyLiftedField = value;
            }
        }
        
        /// <remarks/>
        public InspectionOfBodyAndWindows InspectionOfBodyAndWindows {
            get {
                return this.inspectionOfBodyAndWindowsField;
            }
            set {
                this.inspectionOfBodyAndWindowsField = value;
            }
        }
        
        /// <remarks/>
        public Complectation Complectation {
            get {
                return this.complectationField;
            }
            set {
                this.complectationField = value;
            }
        }
        
        /// <remarks/>
        public AdditionalEquipment AdditionalEquipment {
            get {
                return this.additionalEquipmentField;
            }
            set {
                this.additionalEquipmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Print", Namespace="http://wa.dms.webservice/PrintRequest")]
    public partial class Print1 {
        
        private string dMSRONoField;
        
        private string printTypeField;
        
        private string printAddressField;
        
        private string copyNumberField;
        
        private VHC vHCField;
        
        private FinalInspection finalInspectionField;
        
        /// <remarks/>
        public string DMSRONo {
            get {
                return this.dMSRONoField;
            }
            set {
                this.dMSRONoField = value;
            }
        }
        
        /// <remarks/>
        public string PrintType {
            get {
                return this.printTypeField;
            }
            set {
                this.printTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PrintAddress {
            get {
                return this.printAddressField;
            }
            set {
                this.printAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CopyNumber {
            get {
                return this.copyNumberField;
            }
            set {
                this.copyNumberField = value;
            }
        }
        
        /// <remarks/>
        public VHC VHC {
            get {
                return this.vHCField;
            }
            set {
                this.vHCField = value;
            }
        }
        
        /// <remarks/>
        public FinalInspection FinalInspection {
            get {
                return this.finalInspectionField;
            }
            set {
                this.finalInspectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PrintRequestCompletedEventHandler(object sender, PrintRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrintResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrintResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591